### ISSUE TITLE
Finish toolpath 

### ISSUE THREAD

**Issue by fazekas1974** [vilemnovak/blendercam#95] opened 2017-01-08 11:46 UTC
Hello!
I wanted to make a tutorial finishing tool path, according to the Rough tool path.
Made it but did not look around the object, and completed G-code is only four lines. I attach pictures of the options.
Where can I make a mistake?
![kepernyokep 2017-01-08 12-39-09](https://cloud.githubusercontent.com/assets/16519681/21749508/0239a5e8-d5a0-11e6-9fa9-a0e53c5ac125.png)
![kepernyokep 2017-01-08 12-39-43](https://cloud.githubusercontent.com/assets/16519681/21749510/076b0700-d5a0-11e6-979b-c77ba7945d40.png)
![kepernyokep 2017-01-08 12-39-58](https://cloud.githubusercontent.com/assets/16519681/21749511/0d3ad156-d5a0-11e6-9938-e4f10824a54b.png)
![kepernyokep 2017-01-08 12-40-10](https://cloud.githubusercontent.com/assets/16519681/21749513/144fdc48-d5a0-11e6-909e-89d3b63793a9.png)
![kepernyokep 2017-01-08 12-40-27](https://cloud.githubusercontent.com/assets/16519681/21749514/1aa4f2f4-d5a0-11e6-8c89-3021ba143e34.png)
![kepernyokep 2017-01-08 12-40-43](https://cloud.githubusercontent.com/assets/16519681/21749516/222bef78-d5a0-11e6-8427-4a9bc053f01a.png)
[Vinerfinish.txt](https://github.com/vilemnovak/blendercam/files/692067/Vinerfinish.txt)

**Comment by narvf** [comment] 2017-01-08 19:58
I don't think that i can help - since I mostly used bcam for 2d toolpath generation, but please post blend file - maybe someone else will look into.

**Comment by fazekas1974** [comment] 2017-01-08 21:42
The post my pictures there amid the Vinerfinish.txt.
The rough toolpath generated finish tool path.

**Comment by vilemnovak** [comment] 2017-02-20 20:18
Hi, the problem is that you have a cam path as in input object, put there your source mesh object.
Closing this because it's not a bug.

**Closed by vilemnovak** 2017-02-20 20:18 UTC
