### ISSUE TITLE
spherical cavity

### ISSUE THREAD

**Issue by kylotron** [vilemnovak/blendercam#97] opened 2017-02-17 12:57 UTC
Hello to all.

I realize the spherical cavity to stay of 6.2 mm diameter steel balls. How should I do?

![probe1b](https://cloud.githubusercontent.com/assets/5792338/23066061/e959204c-f518-11e6-93e2-38d857c7b44a.png)

[probe1b.blend.zip](https://github.com/vilemnovak/blendercam/files/783236/probe1b.blend.zip)

**Comment by narvf** [comment] 2017-02-18 10:29
Maybe try pocket operation with ball nose? But I am not sure if this will suits your needs.

**Comment by vilemnovak** [comment] 2017-02-20 19:41
If this should be precise, and mass produced, best would be to get a spherical cutter of that size?
otherwise, try any of the 3d operations, but add more detail to the spherical surfaces.

**Comment by vilemnovak** [comment] 2017-02-20 20:20
also closing, not a bug or issue, we have forum.

**Closed by vilemnovak** 2017-02-20 20:20 UTC
